baseURL = 'https://landchad.net'
languageCode = 'en-us'
title = 'LandChad.net'
theme = 'lugo'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  rssStylesheet = "/rss.xsl"